## Programming Assignment 1 - Linear Algebra and Analytic Geometry
---

**Enter Your Student ID:** 

**Your Name:**
    
**Deadline:**

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [ ]:
# numpy
import numpy as np
from numpy.linalg import inv

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
% matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [1821]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [1822]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 3]
 [0 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [1823]:
# define A,B
A = np.array([[2, 0, 3], [1, -1, 2], [1, -3, 4]])
B = np.array([[2], [1], [2]])
# A = np.array([[-3, -2], [1, 1]])
# B = np.array([[4], [6]])

def solve_with_numpy(A, B):
    ## YOUR CODE HERE
    return np.linalg.solve(A, B)


# show solution
X = solve_with_numpy(A, B)
print(X)

[[-0.5]
 [ 0.5]
 [ 1. ]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [1824]:
A = np.array([[-3, -2], [1, 1]])

A_inv =  np.linalg.inv(A)#YOUR CODE HERE
print(A_inv)

[[-1. -2.]
 [ 1.  3.]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$

---

In [1825]:
# A = np.array([[-3, -2], [1, 1]])
# B = np.array([[4], [6]])
A = np.array([[2, 0, 3], [1, -1, 2], [1, -3, 4]])
B = np.array([[2], [1], [2]])
A_inv = np.linalg.inv(A)

X = A_inv @ B # YOUR CODE HERE

print(X)

[[-0.5]
 [ 0.5]
 [ 1. ]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and use it for computing $X$. Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse.

---

**HINT**: https://en.wikipedia.org/wiki/Moore–Penrose_inverse

In [1883]:
A = np.array([[1, 3], [2, 7], [5, 1]])
B = np.array([[13], [30], [9]])

# print(np.linalg.pinv(A))

A_pseudo_inverse = np.linalg.inv(A.T @ A) @ A.T #YOUR CODE HERE
# print(A_pseudo_inverse)
X = A_pseudo_inverse @ B #YOUR CODE HERE
# X_solve = solve_with_numpy(A, B)
print("X: ", X)
# print("X_solve: ", X_solve)

X:  [[1.]
 [4.]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [1884]:
def Swap(X, row1, row2):
    out = np.copy(X).astype(np.float64)
    for i in range(X.shape[1]):
        temp = out[row1][i]
        out[row1][i] = out[row2][i]
        out[row2][i] = temp
    return out

def Scale(X, row,scale):
    out = np.copy(X).astype(np.float64)
    for i in range(X.shape[1]):
        out[row][i] = out[row][i] * scale
    return out

def AddWithScale(X, row1, row2,scale):
    out = np.copy(X).astype(np.float64)
    for i in range(X.shape[1]):
        out[row2][i] += out[row1][i] * scale

    return out

def gaussian_elim(X):
    m,n = np.shape(X)
    out = np.copy(X).astype(np.float64)
    for col in range(0, n-1):
        if col < m:
            pivotRow = col
            if pivotRow > m-1:
                pivotRow = m-1
            pivot = 0
            rowToSwap = 0
            for row in range(col,m):
                if np.fabs(out[row][col]) > pivot:
                    pivot = out[row][col]
                    rowToSwap = row
            if rowToSwap != 0:
                out = Swap(out,pivotRow,rowToSwap)
            if out[pivotRow][col] != 0:
                scale1 = 1 / out[pivotRow][col]
                out = Scale(out, pivotRow,scale1)
            else:
                scale1 = 1
                out = Scale(out, pivotRow,scale1)
            for row2 in range(0, m):
                if row2 != col:
                    if out[row2][col] != 0:
                        if out[pivotRow][col] != 0:
                            scale = out[row2][col] / out[pivotRow][col]
                        else:
                            scale = 1
                        out = AddWithScale(out,pivotRow,row2,-scale)

    return out


In [1885]:
A = np.array([[1, 0, 1, 1],
              [1, 0, 1, 1],
              [0, 1, 1, 1],
              [1, 1, 1, 0],
              [1, 1, 1, 0]], dtype=np.float64)
print(gaussian_elim(A))
#The result should look like
# [[ 1.,  0.,  0., -1.],
#  [ 0.,  1.,  0., -1.],
#  [-0., -0.,  1.,  2.],
#  [ 0.,  0.,  0.,  0.],
#  [ 0.,  0.,  0.,  0.]]

[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [-0. -0.  1.  2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [1886]:
B = np.array([[2, 0, 3, 1, 0, 2],
              [1, 3, 2, 0, 3, 1],
              [3, 2, 3, 1, 1, 2]])
print(gaussian_elim(B))
#The result should look like
# [[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
#  [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
#  [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]

[[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
 [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
 [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]


We will evaluate your code with many different matrices. 

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [1887]:
def solve_homogeneous(A):
    # YOUR CODE HERE
    twoSol = False
    m,n = np.shape(A)
    out = np.zeros((m,n+1), dtype=np.float64)
    for row in range(m):
        for col in range(n):
            out[row][col] = A[row][col]
    a = gaussian_elim(out)
    x, y = np.shape(a)
    if x < n:
        outa = np.zeros((n,y), dtype=np.float64)
        for row in range(x):
            for col in range(y):
                outa[row][col] = a[row][col]
        a = outa
    result = np.ndarray(n,dtype=np.float64)
    x, y = np.shape(a)
    for i in range(n):
        if i < x:
            if  a[i][i] == 0:
                twoSol = True
                result[i] = 1
                for j in range(i-1,-1,-1):
                    result[j] = (a[j][n] - result[i] * a[j][i] )/a[j][j]
            else:
                result[i] = a[i][n]/a[i][i]
    if result.all() == 0:
        return 0
    else:
        if twoSol:
            return result, result * 2
        else:
            return result

In [1888]:
A = np.array([[2, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.float64)

print(solve_homogeneous(A))
#The result should look like
# 0

0


In [1889]:
B = np.array([[1, 2, 4],
              [1, 2, 4],
              [1, 8, 7]], dtype=np.float64)
print(solve_homogeneous(B))
#The result should look like
# (array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))

# Note that results are not unique

(array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))


In [1890]:
C = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64)
print(solve_homogeneous(C))
#The result should look like
# (array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))

# Note that results are not unique

(array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))


In [1891]:
D = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=np.float64)
print(solve_homogeneous(D))
#The result should look like
# 0

0


We will evaluate your code with many different matrices.

---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [1892]:
def solve_nonhomogeneous(A_aug):
    # YOUR CODE HERE
    twoSolu = False
    m,n = np.shape(A_aug)
    a = gaussian_elim(A_aug)
    x, y = np.shape(a)
    if x < n:
        outa = np.zeros((n,y), dtype=np.float64)
        for row in range(x):
            for col in range(y):
                outa[row][col] = a[row][col]
        a = outa
    result = np.ndarray(n-1,dtype=np.float64)
    x, y = np.shape(a)
    for i in range(n-1):
        if i < x:
            if  a[i][i] == 0:
                if a[i][n-1] != 0:
                    return None
                else:
                    result[i] = 1
                    twoSolu = True
                    for j in range(i-1,-1,-1):
                        result[j] = (a[j][n-1] - result[i] * a[j][i] )/a[j][j]
            else:
                result[i] = a[i][n-1]/a[i][i]
    if result.all() == 0:
        return 0
    else:
        if twoSolu:
            return result, result * 2
        else:
            return result

In [1893]:
A = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 3],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(A))
#The result should look like
# None

None


In [1894]:
B = np.array([
    [1, 0, 1, 6],
    [0, -3, 1, 7],
    [2, 1, 3, 15]
])
print(solve_nonhomogeneous(B))
#The result should look like
# [ 2. -1.  4.]

[ 2. -1.  4.]


In [1895]:
C = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 2],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(C))
#The result should look like
# (array([ 1. , -1.5,  1. ]), array([ 2. , -3.5,  2. ]))

(array([ 1. , -1.5,  1. ]), array([ 2., -3.,  2.]))


We will evaluate your code with many different matrices.

## Task 3: Gram-Schmidt orthogonalization

The Gram-Schmidt algorithm is used for finding an orthonormal basis for the subspace spanned by a set of vectors.

Given a linearly independent set of vectors $S = \lbrace \mathbf{v_1}, \mathbf{v_2}, ..., \mathbf{v_n} \rbrace$, an orthogonal set $S' = \lbrace \mathbf{u_1}, \mathbf{u_2}, ..., \mathbf{u_n} \rbrace $ can be generated under this procedure:


$\mathbf{u_1} = \mathbf{v_1}$\
$\mathbf{u_2} = \mathbf{v_2} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_2})$\
$\mathbf{u_3} = \mathbf{v_3} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_3}) - \textrm{proj}_{\mathbf{u_2}}(\mathbf{v_3})$\
...\
$\mathbf{u_n} = \mathbf{v_n} - \sum_{i=1}^{n-1}\textrm{proj}_{\mathbf{u_i}}(\mathbf{v_n})$,

where $\textrm{proj}_{\mathbf{u}}(\mathbf{v}) = \dfrac{\langle \mathbf{u}, \mathbf{v} \rangle}{\langle \mathbf{u}, \mathbf{u} \rangle}\mathbf{u}$

The orthogonal set is not normalized, you can normalize it by $\mathbf{e_i} = \dfrac{\mathbf{u_i}}{||\mathbf{u_i}||}$

---
**Read more:** https://en.wikipedia.org/wiki/Gram–Schmidt_process

---
**Task 3.1**: Implement a function that finds an orthonormal basis of row vectors for matrix $A$. The *gram_schmidt* function should be according to following specifications: 
* Take as input any matrix $A$.
* Return a matrix with the orthonormal basis vectors as the rows.

---
**NOTE**: The resulting basis should be orthonormal, so each basis vector should be of norm 1.

In [1896]:
# Find orthonormal basis using gram-schmidt 
def gram_schmidt(A):
    # YOUR CODE HERE
    A = np.array(A,dtype=np.float64)
    m, n = np.shape(A)
    out = np.copy(A)
    for i in range(m):
        q = out[i, :]

        for j in range(i):
            q = q - np.dot(out[j, :], out[i, :]) * out[j, :]
            q[np.abs(q) < 1e-10] = 0
        if np.array_equal(q, np.zeros(q.shape)):
            print(out[i, :]," vectors at row ", i, " are not linearly independent ")

        q = q / np.linalg.norm(q)
        for col in range(n):
            out[i][col] = q[col]
    return out[~np.isnan(out).all(axis=1), :]

In [1897]:
A = np.array([[0, -1, 2, 0, 2],
              [1, -3, 1, -1, 2],
              [-3, 4, 1, 2, 1],
              [-1, -3, 5, 0, 7]])

print(gram_schmidt(A))

#The result should look like
# [[ 0.         -0.33333333  0.66666667  0.          0.66666667]
#  [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
#  [-0.57735027  0.         -0.57735027  0.          0.57735027]]

[-1. -3.  5.  0.  7.]  vectors at row  3  are not linearly independent 
[[ 0.         -0.33333333  0.66666667  0.          0.66666667]
 [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
 [-0.57735027  0.         -0.57735027  0.          0.57735027]]


C:\Users\24735\AppData\Local\Temp\ipykernel_15520\3136504255.py:16: RuntimeWarning: invalid value encountered in true_divide
  q = q / np.linalg.norm(q)


We will evaluate your code with many different matrices.

---
**TASK 3.2:** Implement a function that accepts a matrix and returns TRUE if all the rows of that matrix are orthogonal to one another, and each one of them is of length 1. Use this function to verify the output of your *gram_schmidt* function is actually correct. Again, you must program this function yourself, rather than relying on a library function.

You can check whether your algorithms work using the last 6 lines in the code given below.

In [1898]:
def orthogonality_checker(A):
    # YOUR CODE HERE
    A = np.array(A,dtype=np.float64)
    m, n = np.shape(A)
    out = np.copy(A)
    for i in range(m):

        q = out[i, :]

        for j in range(i):
            q = q - np.dot(out[j, :], out[i, :]) * out[j, :]
            q[np.abs(q) < 1e-10] = 0

        if np.array_equal(q, np.zeros(q.shape)):
            print(out[i, :]," vectors at row ", i, " are not linearly independent ")
            return False


        q = q / np.linalg.norm(q)
        for col in range(n):
            out[i][col] = q[col]
    return True

true_test = np.eye(3, 3)
false_test = np.ones((3, 3))
print(true_test)
print(false_test)
print('\nCHECKING TRUE TEST (SHOULD RETURN TRUE):')
print(orthogonality_checker(true_test))
print('\nCHECKING FALSE TEST (SHOULD RETURN FALSE):')
print(orthogonality_checker(false_test))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

CHECKING TRUE TEST (SHOULD RETURN TRUE):
True

CHECKING FALSE TEST (SHOULD RETURN FALSE):
[1. 1. 1.]  vectors at row  1  are not linearly independent 
False


We will evaluate your code with many different matrices.